### PR TITLE
[CR-1945] Add options to customize the checkout style configuration

### PR DESCRIPTION
**Pull request by antonioliv**
Some options are not functioning due to the current deployed version of checkout not including them. Ex: buttonBackgroundColor, accentColor on button, buttonBorderRadius, font size..

Captura de ecrã 2022-09-28, às 17 22 58
Captura de ecrã 2022-09-28, às 17 27 00
Captura de ecrã 2022-09-28, às 17 22 48

### CODE REVIEW

**Comment by Arlanthir** [comment]
I think this is starting to get a bit more visually complicated than it can be.

Maybe hide the UI configuration (right-side Configuration except Hide Details) behind a spoiler/accordion (or just call it "Advanced Configuration" and move it down?) and move the Popup selection to the left-side options as well?

I'm also worried about the copying of the default values to the options (instead of being empty and using the defaults from Checkout). That means that if we change the default values we have to remember to change them here. In fact the inputBackground is already not 100% consistent (`transparent` vs `#fff`).

I hope my concerns were clear, otherwise we can talk them over!

**Comment by antonioliv** [comment]
Added some new features to be more pleasant for the user

https://www.loom.com/share/e58c18b4820d40a98bebae36bdf9a6ca

**Comment by Arlanthir** [comment]
Nice, much better!

What I meant was that it makes sense that if the user doesn't select anything he/she will get the default appearance of the checkout integration. That doesn't happen if we give these default values to the color configurations and then change their defaults in the Checkout itself.

**Comment by antonioliv** [comment]
> Nice, much better!
> 
> What I meant was that it makes sense that if the user doesn't select anything he/she will get the default appearance of the checkout integration. That doesn't happen if we give these default values to the color configurations and then change their defaults in the Checkout itself.
> 
> A safer approach would be to not send the graphical configuration fields if the advanced configuration wasn't used, perhaps.

It's implement like that now. If the `Advanced` option isn't checked, the graphical configuration is not passed.

**Comment by Arlanthir** [comment]
Ah, perfect then!

**Review by Arlanthir — APPROVED** [review]
LGTM

**Pull request merged**
